#!/usr/bin/env bash
###############################################################################
# Cron Job Execution Script (Ollama Version)
# 使用 Ollama 本地模型執行分析 - 完全免費！
###############################################################################

set -e

# 日期和時間
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
TODAY=$(date +"%Y-%m-%d")

# 路徑設定
PROJECT_ROOT="/Users/mhhung/Development/MH/market-intelligence-system"
LOG_FILE="/tmp/market-intelligence-system-ollama.log"

# 環境變數 (macOS cron 環境變數受限,需要明確設定 PATH)
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:$HOME/.local/bin:$HOME/.nvm/versions/node/*/bin"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Ollama 模型設定
export OLLAMA_MODEL="${OLLAMA_MODEL:-gemini-3-pro-preview}"

# 寫入日誌的函數
log() {
    echo "[${TIMESTAMP}] $1" | tee -a "${LOG_FILE}"
}

# 開始執行
log "============================================================"
log "🤖 Market Intelligence System - Daily Analysis (Ollama)"
log "============================================================"
log "📅 使用模型: ${OLLAMA_MODEL}"

# 切換到專案目錄
cd "${PROJECT_ROOT}" || {
    log "❌ 錯誤: 無法切換到專案目錄 ${PROJECT_ROOT}"
    exit 1
}

log "📂 工作目錄: $(pwd)"

# 執行爬蟲 + Ollama 分析
log "🚀 開始執行 make fetch-all + make analyze-ollama..."

# 執行爬蟲
if make fetch-all >> "${LOG_FILE}" 2>&1; then
    log "✅ 爬蟲執行完成!"
else
    log "❌ 爬蟲執行失敗,請檢查日誌: ${LOG_FILE}"
    exit 1
fi

# 執行 Ollama 分析
if make analyze-ollama >> "${LOG_FILE}" 2>&1; then
    log "✅ Ollama 分析完成!"

    # 顯示生成的報告路徑
    MARKET_REPORT="${PROJECT_ROOT}/reports/markdown/market-analysis-${TODAY}.md"
    HOLDINGS_REPORT="${PROJECT_ROOT}/reports/markdown/holdings-analysis-${TODAY}.md"

    if [[ -f "${MARKET_REPORT}" ]]; then
        log "📈 市場分析報告: ${MARKET_REPORT}"
    fi

    if [[ -f "${HOLDINGS_REPORT}" ]]; then
        log "💼 持倉分析報告: ${HOLDINGS_REPORT}"
    fi

    log "✅ 所有任務執行成功!"
else
    log "❌ Ollama 分析失敗,請檢查日誌: ${LOG_FILE}"
    exit 1
fi

# Git 提交報告
log "📝 開始 Git 提交..."

# 檢查是否有變更
if git -C "${PROJECT_ROOT}" status --porcelain | grep -q "reports/markdown"; then
    log "   發現 markdown 報告變更,準備提交..."

    # 添加報告檔案
    git -C "${PROJECT_ROOT}" add reports/markdown/*.md >> "${LOG_FILE}" 2>&1 || true

    # 提交變更
    if git -C "${PROJECT_ROOT}" commit -m "feat(daily): Update analysis reports for ${TODAY}

📊 自動生成的每日市場分析報告 (Ollama ${OLLAMA_MODEL})

- 市場分析報告: market-analysis-${TODAY}.md
- 持倉分析報告: holdings-analysis-${TODAY}.md

🤖 Generated by Market Intelligence System (Cron Job - Ollama)" >> "${LOG_FILE}" 2>&1; then
        log "✅ Git 提交成功!"

        # 推送到 remote
        if git -C "${PROJECT_ROOT}" push origin main >> "${LOG_FILE}" 2>&1; then
            log "✅ Git 推送成功!"
        else
            log "⚠️  Git 推送失敗 (可能需要手動推送或設定認證)"
        fi
    else
        log "⚠️  Git 提交失敗或無內容變更"
    fi
else
    log "   ℹ️  沒有 markdown 報告變更,跳過 Git 提交"
fi

log "============================================================"
log "🤖 Market Intelligence System - Daily Analysis Completed"
log "============================================================"
